### ISSUE TITLE
Add guidance on partnerships with R-Ladies

### ISSUE THREAD

**Issue by maelle** [rladies/rladiesguide#61]
Cc @yabellini 

In the mission https://guide.rladies.org/about/mission/ we have "R-Ladies does not have permanent ties or links to external sponsors or parties. Appropriate sponsorship and support which does not seek to dictate or influence R-Ladies Mission-driven activities/decision-making but enhances the community’s operations and impact is welcomed. Local R-Ladies Organisers are encouraged to gain appropriate support which does not compromise the community’s independence." + non-commercial agenda.

* No official/formal connection with the R-Ladies organization in general to be advertised without agreement of the global team/leadership.
* What rules/tips for chapters.
* Some tips for organizers themselves? What if someone tries to take advantage of their R-Ladies connection to sprinkle diversity on something?

**Comment by yabellini** [comment]
* I agree on point one.  We need to be explicit about the process, but to keep it simple, what about: to ask on the ask_leadership_team channel on the organizer slack or to email to leadership@rladies.org.  We can also write some rules and guidelines for organizations that want to work with R-Ladies.  I saw many emails where Erin has to answer about this non-commercial agenda, etc., and we can have some standard answers and general transparent guidelines.

**Comment by yabellini** [comment]
Tips for organizer: good point. Just yesterday I had a talk with people from Carpentries about organize conferences and the fact of inviting those we call minorities to get diversity points (and not because they really matters). I think the best advice here is to check that they invite you because of what you do (ex: invite me because of data science in agriculture or teaching tech skills). If you are invited to talk about R-Ladies it is also very good and you have to take advantage of those opportunities but check some minimal things such as:
- Do they have CoC? if not, do they agree on add one?
- Are other people belonging to groups that have been systematically excluded from the tech scene part of the conference? What role do they have (keynote, organizers, panelists, chairs?). If not, are they ok to change that?
