### ISSUE TITLE
Best practice for events (and for R-Ladies organizers in general)

### ISSUE THREAD

**Issue by maelle** [rladies/rladiesguide#9]
Tips, published blog posts, etc.

**Comment by chucheria** [comment]
R-Ladies Madrid organisers have gathered some info of what we think worked for us best:

- Organise the year in advanced. Even if you change your plan in the middle is always good to know what to except of this year to know what worked or not.
- Find speakers at least two months before the talk. Even if it is a 5 minutes talk, it will give you peace of mind and time for people to prepare their talk.
- Remember always there's a CoC and you are not afraid to use it! Minorities will feel at home if there's someone there to guard their safe space.

**Comment by maelle** [comment]
@chucheria could you clarify what "you are not afraid to use it" means? E.g. not being afraid to exclude people from the meetup because they broke the CoC?

**Comment by maelle** [comment]
(and thanks a ton!!)

**Comment by chucheria** [comment]
@maelle exactly that, sometimes can be very intimidating tell someone to shut up or that they are not welcome but the CoC actually gives you the authority to do it without being a personal issue.

**Comment by maelle** [comment]
Thank you, and awesome phrasing!

**Comment by silviaegt** [comment]
In the First Annual Meeting of the Mexican Chapters, I took note of this rather brilliant tip for inclusion:

Making an event inclusive can mean to be explicit about things you thought might go without saying, for instance, if **kids** are able to attend the meeting, say it! Chances are people with kids _will_ show up; or, you might wanna tell **people without a personal computer** they can come with a **notebook and a pencil** and write down some ideas and that you will have a few **printed handouts** for them (pairing people could also be an option or hosting your event at a library/working space with available computers to loan)

**Comment by maelle** [comment]
Thank you @silviaegt ! 😀

**Comment by sbnadejda** [comment]
R-Ladies Cotonou has to adapt a lot to make things work. I don't know if these are best practices but it could help a chapter in an area with few resources. The main points that helped us move one are:

- "Members": in order to have people following our meetups we created a form that provides us with basic contact (email, how they want to contribute, what they expect) of people globally interested by R-Ladies Cotonou.

- Communication/Advertisement: We reach out people by email and a WhatsApp group we created to easily reach people. Twitter and Meetup are not commonly used here so we mainly advertise by sending flyers by email to members. We also share them using WhatsApp statuses and asking our personal and professional contacts. But we still post on Twitter and Meetup. 

- Speakers: We encourage participants to make a short presentation of what they like the most about R or would like to know. We support them during the process. (

- Inclusion: There are few orgs promoting women in Science or Tech here so we focus, for now, on having only female speakers and participants. I use "women" because our society is still very strict with gender but I make sure to explain to participants that we include all gender minorities. 

- Funds: So far, only our personal contacts helped us have snacks. We reached with flyers and mention we are opened to any contribution. 

- Logistics: Places to meet have been on the main campus of Cotonou so far. Some lecturers support us by allowing us to use their conference rooms and provide with the needed equipment (but not laptops). We manage to have snacks to make it look more welcoming and promote people talking to each other.

- Online meetups: Since the beginning of the pandemic we did not have online meetups using Zoom because of the costly price of good internet and the bad network issues. However, we opted for WhatsApp meetup (still testing), we send by email the presentation and we set a time for Q&A in the WhatsApp group. Another expensive option I am exploring is to offer a data bundle to participants using the R Consortium grant, when we receive funds, to have a Zoom meetup.

I believe best practices depend on how the chapter organisers can adapt to their reality to make people comfortable at coming to the meetups and also being speakers. I hope you find something helpful! 🙂

**Comment by maelle** [comment]
@sbnadejda thank you, I am digesting your awesome tips. Is your flyer (used to contact sponsors) public? If so I'd add a link to it.

**Comment by sbnadejda** [comment]
You are welcome. Yes, I just uploaded it here on GitHub, you can view them using this [link](https://github.com/sbnadejda/flyers_R-LadiesCtn).

**Comment by maelle** [comment]
mille mercis @sbnadejda

**Comment by maelle** [comment]
Closing because

* I have digested the awesome tips from this thread;
* I now have a strategy of asking more precise questions.
